[options]
girs_dir = "../gir-files"
library = "Gtk-3.0"
target_path = "../gtk"

[[object]]
name = "Gtk.Widget"
type = "widget"
status = "manual"
last_parent = true

[[object]]
name = "Gtk.Container"
type = "widget"
status = "generate"

[[object]]
name = "Gtk.Bin"
type = "widget"
status = "generate"

[[object]]
name = "Gtk.RadioButton"
type = "widget"
status = "generate"
