[options]
work_mode = "normal"
girs_dir = "../gir-files"
library = "Gtk"
version = "3.0"
min_cfg_version = "3.4"
#target_path = "./gtk"
generate_safety_asserts = false
external_libraries = [
   "GLib",
   "Gdk",
   "Pango", 
]

generate = [
    "Gtk.AccelGroup",
    "Gtk.ActionBar",
    "Gtk.Adjustment",
    "Gtk.Alignment",
    "Gtk.AppChooserWidget",
    "Gtk.Application",
    "Gtk.Arrow",
    "Gtk.AspectFrame",
    "Gtk.Bin",
    "Gtk.Box",
    "Gtk.Builder",
    "Gtk.Button",
    "Gtk.ButtonBox",
    "Gtk.Calendar",
    "Gtk.CheckButton",
    "Gtk.ColorButton",
    "Gtk.ColorChooserWidget",
    "Gtk.ComboBoxText",
    "Gtk.CssProvider",
    "Gtk.DrawingArea",
    "Gtk.EventBox",
    "Gtk.Expander",
    "Gtk.FileChooser",
    "Gtk.FileChooserConfirmation",
    "Gtk.FileChooserWidget",
    "Gtk.Fixed",
    "Gtk.FlowBox",
    "Gtk.FlowBoxChild",
    "Gtk.FontButton",
    "Gtk.FontChooser",
    "Gtk.FontChooserWidget",
    "Gtk.Frame",
    "Gtk.Grid",
    "Gtk.HeaderBar",
    "Gtk.IconInfo",
    "Gtk.Image",
    "Gtk.InfoBar",
    "Gtk.Layout",
    "Gtk.LevelBar",
    "Gtk.LinkButton",
    "Gtk.ListBox",
    "Gtk.ListBoxRow",
    "Gtk.Menu",
    "Gtk.MenuButton",
    "Gtk.MenuItem",
    "Gtk.MenuToolButton",
    "Gtk.Misc",
    "Gtk.Notebook",
    "Gtk.NotebookTab",
    "Gtk.Orientable",
    "Gtk.Overlay",
    "Gtk.Paned",
    "Gtk.PlacesSidebar",
    "Gtk.PopoverMenu",
    "Gtk.ProgressBar",
    "Gtk.RadioButton",
    "Gtk.Range",
    "Gtk.RecentChooserWidget",
    "Gtk.RecentManager",
    "Gtk.Revealer",
    "Gtk.Scale",
    "Gtk.ScaleButton",
    "Gtk.ScrolledWindow",
    "Gtk.SearchBar",
    "Gtk.SearchEntry",
    "Gtk.SeparatorMenuItem",
    "Gtk.SeparatorToolItem",
    "Gtk.SizeGroup",
    "Gtk.SpinButton",
    "Gtk.StatusIcon",
    "Gtk.Statusbar",
    "Gtk.ToggleButton",
    "Gtk.ToggleToolButton",
    "Gtk.ToolButton",
    "Gtk.ToolItem",
    "Gtk.ToolItemGroup",
    "Gtk.ToolPalette",
    "Gtk.Toolbar",
    "Gtk.TreeModel",
    "Gtk.TreeSortable",
    "Gtk.Viewport",
    "Gtk.VolumeButton",
    "Gtk.TextBuffer",
    "Gtk.TextIter",
    "Gtk.TreeIter",
    "Gtk.TreePath",
    "Gtk.TreeView",
# bitfields and enums
    "Gtk.AccelFlags",
    "Gtk.Align",
    "Gtk.ApplicationInhibitFlags",
    "Gtk.ArrowType",
    "Gtk.BaselinePosition",
    "Gtk.ButtonBoxStyle",
    "Gtk.ButtonsType",
    "Gtk.CalendarDisplayOptions",
    "Gtk.CellRendererState",
    "Gtk.CornerType",
    "Gtk.DeleteType",
    "Gtk.DialogFlags",
    "Gtk.DirectionType",
    "Gtk.EntryIconPosition",
    "Gtk.EventSequenceState",
    "Gtk.FileChooserAction",
    "Gtk.FileFilterFlags",
    "Gtk.IconSize",
    "Gtk.IconViewDropPosition",
    "Gtk.ImageType",
    "Gtk.InputHints",
    "Gtk.InputPurpose",
    "Gtk.JunctionSides",
    "Gtk.Justification",
    "Gtk.LevelBarMode",
    "Gtk.License",
    "Gtk.MessageType",
    "Gtk.MovementStep",
    "Gtk.NumberUpLayout",
    "Gtk.Orientation",
    "Gtk.PackType",
    "Gtk.PageOrientation",
    "Gtk.PageSet",
    "Gtk.PlacesOpenFlags",
    "Gtk.PolicyType",
    "Gtk.PositionType",
    "Gtk.PrintDuplex",
    "Gtk.PrintPages",
    "Gtk.PrintQuality",
    "Gtk.PropagationPhase",
    "Gtk.RecentFilterFlags",
    "Gtk.RecentSortType",
    "Gtk.Rectangle",
    "Gtk.RegionFlags",
    "Gtk.ReliefStyle",
    "Gtk.ResizeMode",
    "Gtk.RevealerTransitionType",
    "Gtk.ScrollablePolicy",
    "Gtk.ScrollType",
    "Gtk.SelectionMode",
    "Gtk.SensitivityType",
    "Gtk.ShadowType",
    "Gtk.SizeGroupMode",
    "Gtk.SizeRequestMode",
    "Gtk.SortType",
    "Gtk.SpinButtonUpdatePolicy",
    "Gtk.SpinType",
    "Gtk.StackTransitionType",
    "Gtk.StateFlags",
    "Gtk.StateType",
    "Gtk.TextDirection",
    "Gtk.TextSearchFlags",
    "Gtk.TextWindowType",
    "Gtk.ToolPaletteDragTargets",
    "Gtk.ToolbarStyle",
    "Gtk.TreeModelFlags",
    "Gtk.TreeViewColumnSizing",
    "Gtk.TreeViewDropPosition",
    "Gtk.TreeViewGridLines",
    "Gtk.Unit",
    "Gtk.WidgetHelpType",
    "Gtk.WindowPosition",
    "Gtk.WindowType",
    "Gtk.WrapMode",
]

manual = [
    "GLib.Error",
    "Gdk.Screen",
    "Gdk.Window",
    "GdkPixbuf.Pixbuf",
    "GdkPixbuf.PixbufAnimation",
    "Gio.Application",
    "GLib.Variant",
    "GLib.VariantTy",
    "GLib.VariantType",
    "GObject.Value",
    "Gtk.Actionable",
    "Gtk.Container",
    "Gtk.Dialog",
    "Gtk.RecentData",
    "Gtk.RecentInfo",
    "Gtk.Widget",
    "Gtk.Window",
    "Gdk.Rectangle",
#    "Gdk.RGBA",
    "cairo.RectangleInt",
]

ignore = [
    "Gtk.Activatable",
]

[[object]]
name = "Gtk.AppChooserDialog"
status = "generate"
[[object.function]]
name = "get_widget"
[object.function.return]
nullable = false

[[object]]
name = "Gtk.GLArea"
status = "generate"
module_name = "gl_area"

[[object]]
name = "Gtk.WidgetPath"
status = "generate"
[[object.function]]
pattern = 'iter_has_q\w+'
ignore = true

[[object]]
name = "Gtk.Label"
status = "generate"
[[object.signal]]
name = "activate-link"
inhibit = true

[[object]]
name = "Gtk.PageSetup"
status = "generate"
[[object.function]]
name = "set_paper_size"
[[object.function.parameter]]
name = "size"
const = true

[[object]]
name = "Gtk.PaperSize"
status = "generate"
[[object.function]]
name = "is_ipp"
version = "3.16"

[[object]]
name = "Gtk.Popover"
status = "generate"
version = "3.12"

[[object]]
name = "Gtk.PrintSettings"
status = "generate"
    [[object.function]]
    name = "get_page_ranges"
    ignore = true
    [[object.function]]
    name = "set_page_ranges"
    ignore = true
    [[object.function]]
    name = "set_paper_size"
        [[object.function.parameter]]
        name = "paper_size"
        const = true

[[object]]
name = "Gtk.ComboBox"
status = "generate"

[[object]]
name = "Gtk.TreeSelection"
status = "generate"

[[object]]
name = "Gtk.MenuShell"
status = "generate"
    [[object.signal]]
    name = "move-current"
#only for example
    ignore = true
